[project]
name = "app-rrhh-api"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.110.0",
  "uvicorn[standard]>=0.27.0",
  "python-jose[cryptography]>=3.3.0",
  "pydantic>=2.6.0",
]

[tool.uvicorn]
factory = false
